package org.example.bundles;

import java.util.ListResourceBundle;

public class AppointmentOperationResources_fr extends ListResourceBundle {
    private Object[][] contents = {
            {"id", "ID"},
            {"save", "Enregister"},
            {"cancel", "Annuler"},
            {"dataLostNotification", "Toutes les données des champs de texte seront perdues"},
            {"confirmationQuestion", "Êtes-vous d'accord avec ça?"},
            {"noEmptyFields", "Veuillez remplir tous les champs vides."},
            {"appointmentId", "Id de Rendez-vous"},
            {"overlappingAppointmentError", "Ce rendez-vous chevauche un autre rendez-vous pour ce client et ne peut pas être ajouté. Rendez-vous qui se chevauchent:"},
            {"appointmentStart", "Début du rendez-vous"},
            {"appointmentEnd", "Fin du rendez-vous"},
            {"outsideOfWorkHours","Tous les rendez-vous doivent être planifiés pendant les heures de travail: de 8 h à 22 h. Heure de l'Est"},
            {"endTimeBeforeStartTimeError", "L'heure de fin doit être postérieure à l'heure de début sélectionnée."},
            {"endDateBeforeStartDateError", "La date de fin ne peut pas être une date antérieure à la date de début sélectionnée."},
            {"invalidCustomerIdError", "Le numéro client saisi pour ce rendez-vous ne correspond pas à un client de la base de données. Veuillez saisir un identifiant client valide."},
            {"invalidUserIdError", "L'ID utilisateur saisi pour ce rendez-vous ne correspond pas à un utilisateur de la base de données. Veuillez saisir un ID utilisateur valide."},
            {"title", "Titre"},
            {"description", "La Description"},
            {"type", "Catégorie"},
            {"location", "Emplacement"},
            {"startDate", "Date de Début"},
            {"startTime", "Heure de Début"},
            {"endDate", "Date de Fin"},
            {"endTime", "Heure de Fin"},
            {"customerId", "Identification du Client"},
            {"contact", "Le Contact"},
            {"userId", "Identifiant D'utilisateur"},
            {"addAppointment", "Ajouter Un Rendez-vous"},
            {"modifyAppointment", "Modifier Un Rendez-vous"},
            {"timeFormat", "Entrer l'heure au format 24 heures"},
            {"invalidHourError", "Les heures doivent être au format 24 heures entre 0 et 23"},
            {"invalidMinuteError", "Les minutes doivent être comprises entre 0 et 59"},
            {"save","Enregister"},
            {"cancel", "Annuler"},
            {"autoGenerated", "Genere Automatiquement"}
    };

    @Override
    protected Object[][] getContents() {
        return contents;
    }
}
